server:
  port: 8081

spring:
  application:
    name: command-api
  datasource:
    url: jdbc:mysql://localhost:3307/growup_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN