version: '3.8'

services:
  kafka:
    # 🔥 카프카 공식 개발사가 만든 로컬 전용 KRaft 이미지! (태그 에러 절대 안 남)
    image: confluentinc/confluent-local:7.5.0
    container_name: local-kafka
    ports:
      - "9092:9092"
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:alpine
    container_name: local-redis
    ports:
      - "6379:6379"
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: growup_db
    command:
      - --server-id=1                 # Master 고유 ID
      - --log-bin=mysql-bin           # 변경 내역을 기록할 Binlog 활성화 (복제의 핵심!)
      - --binlog-format=ROW
    volumes:
      - ./master-init.sql:/docker-entrypoint-initdb.d/init.sql # 초기화 스크립트 실행

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    ports:
      - "3307:3306" # 로컬에서는 3307 포트로 접속!
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --server-id=2                 # Slave 고유 ID
      - --relay-log=mysql-relay-bin   # Master의 Binlog를 받아올 릴레이 로그
      - --read-only=1                 # ★ Slave는 무조건 읽기 전용으로 잠금!
    depends_on:
      - mysql-master