server:
  port: ${SERVER_PORT:8080} # 읽기 서버는 8082 포트로 실행

spring:
  application:
    name: query-service
  datasource:
    url: jdbc:mysql://localhost:3307/growup_db
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 200ms
  kafka:
    consumer:
      group-id: query-consumer-group
      client-id: ${MY_SERVER_ID:default-client}
      bootstrap-servers: localhost:9092
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    root: INFO
    org.example: debug
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j.circuitbreaker:
  instances:
    redisCircuitBreaker: # 차단기 이름
      slidingWindowSize: 10 # 최근 10개의 요청을 기준으로 판단
      failureRateThreshold: 10 # 그 중 50% 이상 실패하면 두꺼비집 내림 (OPEN)
      waitDurationInOpenState: 10s # OPEN 상태에서 10초 동안은 무조건 Fallback 실행 (Redis 안 찌름)
      permittedNumberOfCallsInHalfOpenState: 1 # 10초 뒤에 3개만 테스트로 찔러봄 (HALF-OPEN)
      minimumNumberOfCalls: 5 # 최소 5번은 요청이 들어와야 실패율 계산 시작
      automaticTransitionFromOpenToHalfOpenEnabled: true
