server:
  port: 0 # 읽기 서버는 8082 포트로 실행

spring:
  application:
    name: query-api
  datasource:
    url: jdbc:mysql://localhost:3307/growup_db
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/